version: '3.8'
services:
  db:
    container_name: student-grading-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/docker-workspace/student-grading/db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  default:
    name: student-grading-network
    driver: bridge