version: '3.8'
services:
  web :
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - student-grading-network

  db:
    container_name: student-grading-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME-student_db}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
    ports:
      - ${DB_PORT_ON_DOCKER_HOST-5432}:${DB_PORT_ON_CONTAINER-5432}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - student-grading-network
    expose:
      - 5432

volumes:
  db:

networks:
  student-grading-network: