micronaut:
  server:
    port: 8080
  application:
    name: studentGradingMicronaut

db:
  host: localhost
  port: 5432
  name: student_db

datasources:
  default:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES


jpa:
  default:
    entity-scan:
      packages: in.one2n.studentgrading.entity

jpa.default.properties.hibernate.hbm2ddl.auto: update

liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'


netty:
  default:
    allocator:
      max-order: 3
