liquibase:
  enabled: true
  url: jdbc:postgresql://${embedded.postgresql.host}:${embedded.postgresql.port}/${embedded.postgresql.schema}
  user: ${embedded.postgresql.user}
  password: ${embedded.postgresql.password}
  change-log: classpath:db/changelog.xml
  datasource:
    url: jdbc:postgresql://${embedded.postgresql.host}:${embedded.postgresql.port}/${embedded.postgresql.schema}
    username: ${embedded.postgresql.user}
    password: ${embedded.postgresql.password}
    name: student_db

